baseURL = 'https://yajnamurti-my.netlify.app/'
languageCode = 'en-us'
title = 'My mind'
theme="beautifulhugo"


[Params]
subtitle = "A place for my thoughts"


[Author]
email = "yajnamurti2@gmail.com"
facebook = "Yajnamurti"


