baseURL = 'https://yajnamurtidas.netlify.app'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme="beautifulhugo"


[Params]
subtitle = "A place for my thoughts"


[Author]
email = "yajnamurti2@gmail"
facebook = "Yajnamurti"
